# Generated by Django 4.2.1 on 2023-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0002_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="department",
            new_name="department",
        ),
        migrations.AlterField(
            model_name="department",
            name="image",
            field=models.ImageField(blank=True, upload_to="department"),
        ),
    ]
