# Generated by Django 4.2.1 on 2023-05-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0004_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
